'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Download, Calendar, User, Eye, Activity, Mic, MessageSquare } from 'lucide-react';
import { generateInvoicePDF } from '@/lib/pdf-generator';

interface Video {
  id: string;
  title: string;
  speaker: string;
  uploadDate: string;
  duration: string;
  overallScore: number;
  bodyLanguageScore: number;
  vocalToneScore: number;
  wordPowerScore: number;
  thumbnail: string;
}

const mockVideos: Video[] = [
  {
    id: '1',
    title: 'Quarterly Sales Presentation',
    speaker: 'John Smith',
    uploadDate: '2024-01-15',
    duration: '12:34',
    overallScore: 78,
    bodyLanguageScore: 82,
    vocalToneScore: 75,
    wordPowerScore: 77,
    thumbnail: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=400'
  },
  {
    id: '2',
    title: 'Product Launch Demo',
    speaker: 'Sarah Johnson',
    uploadDate: '2024-01-12',
    duration: '18:45',
    overallScore: 85,
    bodyLanguageScore: 88,
    vocalToneScore: 82,
    wordPowerScore: 85,
    thumbnail: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=400'
  },
  {
    id: '3',
    title: 'Team Meeting Facilitation',
    speaker: 'Mike Davis',
    uploadDate: '2024-01-10',
    duration: '25:12',
    overallScore: 72,
    bodyLanguageScore: 70,
    vocalToneScore: 74,
    wordPowerScore: 72,
    thumbnail: 'https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg?auto=compress&cs=tinysrgb&w=400'
  }
];

interface VideoListProps {
  filters: {
    search: string;
    dateFrom: string;
    dateTo: string;
  };
}

export function VideoList({ filters }: VideoListProps) {
  const router = useRouter();

  const filteredVideos = mockVideos.filter(video => {
    const matchesSearch = video.speaker.toLowerCase().includes(filters.search.toLowerCase()) ||
                         video.title.toLowerCase().includes(filters.search.toLowerCase());
    
    const matchesDateFrom = !filters.dateFrom || new Date(video.uploadDate) >= new Date(filters.dateFrom);
    const matchesDateTo = !filters.dateTo || new Date(video.uploadDate) <= new Date(filters.dateTo);
    
    return matchesSearch && matchesDateFrom && matchesDateTo;
  });

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-600';
    if (score >= 70) return 'text-yellow-600';
    return 'text-red-600';
  };

  const handleViewReport = (video: Video) => {
    router.push(`/videos/${video.id}/report`);
  };

  const handleDownloadReport = (video: Video) => {
    // Generate mock invoice data for the video report
    const reportData = {
      invoiceNumber: `RPT-${video.id}`,
      issueDate: new Date().toISOString().split('T')[0],
      dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      clientName: video.speaker,
      clientEmail: `${video.speaker.toLowerCase().replace(' ', '.')}@company.com`,
      clientAddress: 'Communication Analytics Report\nGenerated by CommAnalytics Platform',
      items: [
        {
          id: '1',
          description: `Video Analysis Report - ${video.title}`,
          quantity: 1,
          rate: 0,
          amount: 0
        },
        {
          id: '2',
          description: `Overall Communication Score: ${video.overallScore}/100`,
          quantity: 1,
          rate: 0,
          amount: 0
        },
        {
          id: '3',
          description: `Body Language Score: ${video.bodyLanguageScore}/100`,
          quantity: 1,
          rate: 0,
          amount: 0
        },
        {
          id: '4',
          description: `Vocal Tone Score: ${video.vocalToneScore}/100`,
          quantity: 1,
          rate: 0,
          amount: 0
        },
        {
          id: '5',
          description: `Word Power Score: ${video.wordPowerScore}/100`,
          quantity: 1,
          rate: 0,
          amount: 0
        }
      ],
      notes: `This report contains detailed analysis of the video "${video.title}" presented by ${video.speaker} on ${new Date(video.uploadDate).toLocaleDateString()}. The analysis includes comprehensive evaluation of communication skills across multiple dimensions.`,
      terms: 'This report is generated by CommAnalytics AI-powered video analysis platform.',
      taxRate: 0
    };

    generateInvoicePDF(reportData, 0, 0, 0);
  };

  return (
    <div>
      <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
        {filteredVideos.map((video) => (
          <Card key={video.id} className="border-0 shadow-sm hover:shadow-md transition-shadow duration-200">
            <CardHeader className="p-0">
              <div className="relative">
                <img
                  src={video.thumbnail}
                  alt={video.title}
                  className="w-full h-48 object-cover rounded-t-lg"
                />
                <div className="absolute bottom-3 right-3 bg-black/80 text-white px-2 py-1 rounded text-xs">
                  {video.duration}
                </div>
              </div>
            </CardHeader>
            
            <CardContent className="p-6">
              {/* Title & Speaker Info */}
              <div className="mb-6">
                <CardTitle className="text-lg font-medium text-gray-900 mb-3">
                  {video.title}
                </CardTitle>
                <div className="flex items-center space-x-4 text-sm text-gray-500">
                  <div className="flex items-center space-x-1">
                    <User className="w-3 h-3" />
                    <span>{video.speaker}</span>
                  </div>
                  <div className="flex items-center space-x-1">
                    <Calendar className="w-3 h-3" />
                    <span>{new Date(video.uploadDate).toLocaleDateString()}</span>
                  </div>
                </div>
              </div>

              {/* Minimalist Score Display */}
              <div className="mb-6">
                <div className="flex items-center justify-between mb-4">
                  <span className="text-sm text-gray-600">Overall Score</span>
                  <span className={`text-lg font-semibold ${getScoreColor(video.overallScore)}`}>
                    {video.overallScore}/100
                  </span>
                </div>
                
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <Activity className="w-4 h-4 text-gray-400" />
                      <span className="text-sm text-gray-600">Body Language</span>
                    </div>
                    <span className={`text-sm font-medium ${getScoreColor(video.bodyLanguageScore)}`}>
                      {video.bodyLanguageScore}
                    </span>
                  </div>
                  
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <Mic className="w-4 h-4 text-gray-400" />
                      <span className="text-sm text-gray-600">Vocal Tone</span>
                    </div>
                    <span className={`text-sm font-medium ${getScoreColor(video.vocalToneScore)}`}>
                      {video.vocalToneScore}
                    </span>
                  </div>
                  
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <MessageSquare className="w-4 h-4 text-gray-400" />
                      <span className="text-sm text-gray-600">Word Power</span>
                    </div>
                    <span className={`text-sm font-medium ${getScoreColor(video.wordPowerScore)}`}>
                      {video.wordPowerScore}
                    </span>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex space-x-2">
                <Button
                  className="flex-1 bg-gradient-to-r from-blue-600 to-green-500 hover:from-blue-700 hover:to-green-600 text-white shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105"
                  size="sm"
                  onClick={() => handleViewReport(video)}
                >
                  <Eye className="w-4 h-4 mr-2" />
                  View Report
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleDownloadReport(video)}
                  className="border-gray-300 hover:bg-gray-50"
                >
                  <Download className="w-4 h-4" />
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {filteredVideos.length === 0 && (
        <div className="text-center py-12">
          <div className="text-gray-500">No videos found matching your criteria.</div>
        </div>
      )}
    </div>
  );
}